#!/usr/bin/env bash
# dotfriend — Code generation: create dotfiles repo from selections
# shellcheck shell=bash

set -euo pipefail

# shellcheck source=common.sh
source "$(dirname "${BASH_SOURCE[0]}")/common.sh"

# shellcheck source=gum.sh
source "$(dirname "${BASH_SOURCE[0]}")/gum.sh"

# shellcheck source=manifest.sh
source "$(dirname "${BASH_SOURCE[0]}")/manifest.sh"

# ─────────────────────────────────────────────────────────────
# Paths
# ─────────────────────────────────────────────────────────────

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TEMPLATES_DIR="${SCRIPT_DIR}/../templates"
SELECTIONS_FILE="${DOTFRIEND_CACHE_DIR}/selections.json"

# ─────────────────────────────────────────────────────────────
# State
# ─────────────────────────────────────────────────────────────

GEN_DIR=""
GEN_BACKUP_ROOT=""
GEN_DRY_RUN="false"
GEN_GITHUB_BACKED_UP="false"
GEN_GITHUB_URL=""
GEN_GITHUB_STATUS_MESSAGE=""

# ─────────────────────────────────────────────────────────────
# JSON reading (jq preferred, naive fallback)
# ─────────────────────────────────────────────────────────────

_jq_or_fallback() {
  local file="$1" query="$2"
  if command -v jq >/dev/null 2>&1; then
    jq -r "$query" "$file" 2>/dev/null || true
  else
    # Very naive fallback for simple array extraction
    grep -oP '"'"$query"'"\s*:\s*\[\K[^\]]*' "$file" 2>/dev/null || true
  fi
}

_jq_str() {
  local file="$1" query="$2"
  if command -v jq >/dev/null 2>&1; then
    jq -r "$query // empty" "$file" 2>/dev/null || true
  else
    true
  fi
}

_selected_repo_name() {
  local repo_name
  repo_name="$(_jq_str "$SELECTIONS_FILE" '.github.repo_name')"
  if [[ -z "$repo_name" || "$repo_name" == "null" ]]; then
    repo_name="dotfiles"
  fi
  printf '%s' "$repo_name"
}

_selected_agent_ids() {
  if command -v jq >/dev/null 2>&1; then
    jq -r '.agents[]? | .id' "$SELECTIONS_FILE" 2>/dev/null || true
  fi
}

_repo_path_for_dotfile() {
  local dotfile="$1"
  case "$dotfile" in
    .gitconfig)
      printf '%s' "config/git/${dotfile}"
      ;;
    *)
      printf '%s' "zsh/${dotfile}"
      ;;
  esac
}

_copy_tree_filtered() {
  local src="$1" dest="$2"
  ensure_dir "$dest"

  if command -v rsync >/dev/null 2>&1; then
    rsync -a \
      --exclude '.git/' \
      --exclude '.gitignore' \
      --exclude 'node_modules/' \
      --exclude '.next/' \
      --exclude 'dist/' \
      --exclude 'build/' \
      --exclude 'coverage/' \
      --exclude '__pycache__/' \
      --exclude '.pytest_cache/' \
      --exclude '.cache/' \
      --exclude 'tmp/' \
      --exclude 'temp/' \
      "$src/" "$dest/"
    return 0
  fi

  cp -a "$src/." "$dest/"
  find "$dest" \
    \( -name '.git' -o -name 'node_modules' -o -name '.next' -o -name 'dist' -o -name 'build' -o -name 'coverage' -o -name '__pycache__' -o -name '.pytest_cache' -o -name '.cache' -o -name 'tmp' -o -name 'temp' \) \
    -prune -exec rm -rf {} + 2>/dev/null || true
  find "$dest" -name '.gitignore' -type f -delete 2>/dev/null || true
}

_sanitize_agent_file_copy() {
  local agent_id="$1" dest="$2"

  if [[ "$agent_id" != "claude" || "$(basename "$dest")" != "settings.json" ]]; then
    return 0
  fi

  if command -v jq >/dev/null 2>&1; then
    local tmpfile
    tmpfile="$(mktemp)"
    if jq 'del(.hooks)' "$dest" > "$tmpfile" 2>/dev/null; then
      mv "$tmpfile" "$dest"
      log_info "Removed active Claude hooks from copied settings.json"
      return 0
    fi
    rm -f "$tmpfile"
  fi

  if command -v python3 >/dev/null 2>&1; then
    if python3 - "$dest" <<'PY'
import json
import sys

path = sys.argv[1]
with open(path, "r", encoding="utf-8") as f:
    data = json.load(f)

data.pop("hooks", None)

with open(path, "w", encoding="utf-8") as f:
    json.dump(data, f, indent=2)
    f.write("\n")
PY
    then
      log_info "Removed active Claude hooks from copied settings.json"
      return 0
    fi
  fi

  log_warn "Could not sanitize copied Claude settings.json; hooks remain active in backup"
}

_print_command_failure_log() {
  local logfile="$1"
  [[ -s "$logfile" ]] || return 0

  while IFS= read -r line; do
    printf '   %s\n' "$line" >&2
  done < "$logfile"
}

# ─────────────────────────────────────────────────────────────
# File generation helpers
# ─────────────────────────────────────────────────────────────

_generate_brewfile() {
  local out="${GEN_DIR}/Brewfile"
  log_info "Generating Brewfile..."

  {
    printf "# Brewfile — generated by dotfriend\\n"
    printf "# Edit with care.\\n\\n"

    # Taps
    local taps; taps="$(_jq_str "$SELECTIONS_FILE" '.taps | if . then join("\n") else "" end')"
    if [[ -n "$taps" ]]; then
      printf "# Taps\\n"
      while IFS= read -r tap; do
        [[ -z "$tap" ]] && continue
        printf 'tap "%s"\\n' "$tap"
      done <<< "$taps"
      printf "\\n"
    fi

    # Formulae
    local formulae; formulae="$(_jq_str "$SELECTIONS_FILE" '.formulae | if . then join("\n") else "" end')"
    if [[ -n "$formulae" ]]; then
      printf "# Formulae\\n"
      while IFS= read -r f; do
        [[ -z "$f" ]] && continue
        printf 'brew "%s"\\n' "$f"
      done <<< "$formulae"
      printf "\\n"
    fi

    # Casks (from apps)
    local apps_json; apps_json="$(_jq_str "$SELECTIONS_FILE" '.apps')"
    if [[ -n "$apps_json" ]]; then
      printf "# Casks\\n"
      while IFS= read -r app; do
        [[ -z "$app" ]] && continue
        # app format from wizard: "App Name|cask:token|cask" or "App Name|mas:token,id:123|mas"
        if [[ "$app" == *"|cask:"* ]]; then
          local cask; cask="${app#*|cask:}"
          cask="${cask%%|*}"
          printf 'cask "%s"\\n' "$cask"
        fi
      done <<< "$apps_json"
      printf "\\n"
    fi

    # MAS apps
    if [[ -n "$apps_json" ]]; then
      printf "# Mac App Store\\n"
      while IFS= read -r app; do
        [[ -z "$app" ]] && continue
        if [[ "$app" == *"|mas:"* ]]; then
          local mas_part; mas_part="${app#*|mas:}"
          mas_part="${mas_part%%|*}"
          local mas_name mas_id
          mas_name="${mas_part%%,*}"
          mas_id="${mas_part##*id:}"
          printf 'mas "%s", id: %s\\n' "$mas_name" "$mas_id"
        fi
      done <<< "$apps_json"
      printf "\\n"
    fi

    # npm globals (not in Brewfile, but note: we may want node in Brewfile)
    # We handle npm in install.sh, not Brewfile
  } > "$out"

  log_ok "Brewfile generated"
}

_replace_placeholder() {
  local file="$1" placeholder="$2" content_file="$3"
  local temp; temp="$(mktemp)"
  awk -v ph="$placeholder" -v cf="$content_file" '
    index($0, ph) > 0 {
      while ((getline line < cf) > 0) {
        print line
      }
      close(cf)
      next
    }
    { print }
  ' "$file" > "$temp"
  mv "$temp" "$file"
}

_generate_install_sh() {
  local template="${TEMPLATES_DIR}/install.sh"
  local out="${GEN_DIR}/install.sh"
  log_info "Generating install.sh..."

  cp "$template" "$out"

  # Substitute basic placeholders
  local repo_name; repo_name="$(_selected_repo_name)"
  sed -i.bak "s|{{BACKUP_ROOT:-\${HOME}/.dotfiles-backup}}|${GEN_BACKUP_ROOT}|g" "$out"
  sed -i.bak "s|{{INSTALL_MAS:-true}}|true|g" "$out"
  sed -i.bak "s|{{BREW_UPGRADE:-true}}|true|g" "$out"
  sed -i.bak "s|{{INSTALL_DOTFRIEND:-true}}|true|g" "$out"
  sed -i.bak "s|{{INSTALL_VALIDATE:-false}}|false|g" "$out"
  sed -i.bak "s|{{DRY_RUN:-false}}|false|g" "$out"
  rm -f "${out}.bak"

  # Build blocks into temp files and replace placeholders inline
  local tmpfile; tmpfile="$(mktemp)"

  _build_xcode_block > "$tmpfile"
  _replace_placeholder "$out" "{{XCODE_BLOCK}}" "$tmpfile"

  _build_symlinks_block > "$tmpfile"
  _replace_placeholder "$out" "{{SYMLINKS_BLOCK}}" "$tmpfile"

  _build_copies_block > "$tmpfile"
  _replace_placeholder "$out" "{{COPIES_BLOCK}}" "$tmpfile"

  _build_agent_rsync_block > "$tmpfile"
  _replace_placeholder "$out" "{{AGENT_RSYNC_BLOCK}}" "$tmpfile"

  _build_npm_block > "$tmpfile"
  _replace_placeholder "$out" "{{NPM_BLOCK}}" "$tmpfile"

  _build_vscode_block > "$tmpfile"
  _replace_placeholder "$out" "{{VSCODE_BLOCK}}" "$tmpfile"

  _build_cursor_block > "$tmpfile"
  _replace_placeholder "$out" "{{CURSOR_BLOCK}}" "$tmpfile"

  _build_dock_block > "$tmpfile"
  _replace_placeholder "$out" "{{DOCK_BLOCK}}" "$tmpfile"

  _build_duti_block > "$tmpfile"
  _replace_placeholder "$out" "{{DUTI_BLOCK}}" "$tmpfile"

  _build_telemetry_block > "$tmpfile"
  _replace_placeholder "$out" "{{TELEMETRY_BLOCK}}" "$tmpfile"

  rm -f "$tmpfile"

  chmod +x "$out"
  log_ok "install.sh generated"
}

_generate_bootstrap_sh() {
  local template="${TEMPLATES_DIR}/bootstrap.sh"
  local out="${GEN_DIR}/bootstrap.sh"
  log_info "Generating bootstrap.sh..."

  cp "$template" "$out"

  local repo_name; repo_name="$(_selected_repo_name)"
  local repo_url="https://github.com/$(gh api user -q '.login' 2>/dev/null || echo 'YOUR_USERNAME')/${repo_name}.git"

  sed -i.bak "s|{{REPO_URL}}|${repo_url}|g" "$out"
  sed -i.bak "s|{{DOTFILES_DIR}}|\${HOME}/${repo_name}|g" "$out"
  sed -i.bak "s|{{RUN_DOTFILES_INSTALL:-true}}|true|g" "$out"
  rm -f "${out}.bak"

  chmod +x "$out"
  log_ok "bootstrap.sh generated"
}

_generate_gitignore() {
  local out="${GEN_DIR}/.gitignore"
  log_info "Generating .gitignore..."
  cat > "$out" <<'GITIGNORE_EOF'
### Secrets and keys ###
secrets/
secrets/*.key
secrets/*.pem
secrets/*.p12
secrets/*.enc
*.env
.env.*
.ssh/id_*
.ssh/*_rsa
.ssh/*_ed25519
.config/sops/

### Caches ###
__pycache__/
*.pyc
*.pyo
*.egg-info/
.pytest_cache/
*.cache
.cache/
node_modules/
.next/cache/

### OS files ###
.DS_Store
.AppleDouble
.LSOverride
Thumbs.db

### Editor files ###
.vscode/
.idea/
*.swp
*.swo
*~

### Logs ###
*.log
logs/

### Temporary files ###
tmp/
temp/
*.tmp
*.bak
*.backup

### Build artifacts ###
dist/
build/
.next/
out/
target/
GITIGNORE_EOF
  log_ok ".gitignore generated"
}

_generate_locations_md() {
  local out="${GEN_DIR}/locations.md"
  log_info "Generating locations.md..."

  {
    printf "# Config Location Reference\\n\\n"
    printf "Auto-generated by dotfriend.\\n\\n"
    printf "## Agent Tools\\n\\n"
    local agents; agents="$(_jq_str "$SELECTIONS_FILE" '.agents | if . then join("\n") else "" end')"
    if [[ -n "$agents" ]]; then
      while IFS= read -r agent; do
        [[ -z "$agent" ]] && continue
        local agent_id; agent_id="${agent%%|*}"
        printf -- "- **%s**: see agent-tools.json for canonical paths\\n" "$agent_id"
      done <<< "$agents"
    fi
    printf "\\n## Dotfiles\\n\\n"
    local dotfiles; dotfiles="$(_jq_str "$SELECTIONS_FILE" '.dotfiles | if . then join("\n") else "" end')"
    if [[ -n "$dotfiles" ]]; then
      while IFS= read -r df; do
        [[ -z "$df" ]] && continue
        printf -- "- \`~/%s\` → symlinked to repo\\n" "$df"
      done <<< "$dotfiles"
    fi
  } > "$out"

  log_ok "locations.md generated"
}

_generate_repo_metadata() {
  local metadata_dir="${GEN_DIR}/.dotfriend"
  log_info "Generating repo metadata..."

  ensure_dir "$metadata_dir"
  cp "${SCRIPT_DIR}/agent-tools.json" "${metadata_dir}/agent-tools.json"
  cp "$SELECTIONS_FILE" "${metadata_dir}/selections.json"

  log_ok "Repo metadata generated"
}

_generate_restore_manifest() {
  log_info "Generating restore manifest..."
  manifest_write_for_generated_repo "$GEN_DIR" "$SELECTIONS_FILE" "${SCRIPT_DIR}/agent-tools.json"
  log_ok "Restore manifest generated"
}

_generate_readme_md() {
  local out="${GEN_DIR}/README.md"
  local repo_name
  repo_name="$(_selected_repo_name)"

  log_info "Generating README.md..."

  {
    printf "# %s\n\n" "$repo_name"
    printf '%s\n\n' "Generated by dotfriend. This repo is meant to be both your restore source on a new Mac and your day-to-day backup target on your current machine."
    printf '%s\n\n' "## New Machine Setup"
    printf '%s\n\n' "If this repo is already cloned locally, run:"
    printf '```bash\n'
    printf './install.sh\n'
    printf '```\n\n'
    printf '%s\n\n' "For a safer preview first:"
    printf '```bash\n'
    printf 'DRY_RUN=true ./install.sh\n'
    printf '```\n\n'
    printf '%s\n\n' "Run validation after install if you want a quick sanity check:"
    printf '```bash\n'
    printf './scripts/validate.sh --all\n'
    printf '```\n\n'
    printf '%s\n\n' '`install.sh` also installs the `dotfriend` CLI when needed and registers this clone as the repo that `dotfriend sync` should maintain.'
    printf '%s\n\n' '`bootstrap.sh` is the first-run helper for a brand-new Mac when you want Homebrew/Xcode setup and repo cloning handled before `install.sh` runs.'
    printf '%s\n\n' "## Sync Back Into This Repo"
    printf '%s\n\n' "Use dotfriend as the normal orchestrator for ongoing sync:"
    printf '```bash\n'
    printf 'dotfriend sync\n'
    printf '```\n\n'
    printf '%s\n\n' "If dotfriend is unavailable, this repo also includes a portable fallback sync script. Preview changes from your current machine:"
    printf '```bash\n'
    printf './scripts/backup.sh --dry-run\n'
    printf '```\n\n'
    printf '%s\n\n' "Sync and auto-commit tracked changes locally:"
    printf '```bash\n'
    printf './scripts/backup.sh --commit\n'
    printf '```\n\n'
    printf '%s\n\n' "These sync flows update the generated repo content that dotfriend tracks, including your Brewfile, npm globals, tracked dotfiles/configs, selected agent configs, and VS Code/Cursor extension ID lists."
    printf '%s\n\n' "## What Gets Restored"
    printf '%s\n' '- Homebrew taps, formulae, casks, and Mac App Store apps from `Brewfile`'
    printf '%s\n' '- Global npm packages from `npm-global.txt`'
    printf '%s\n' '- Tracked shell dotfiles and app config directories'
    printf '%s\n' '- Selected agent config files and managed subdirectories'
    printf '%s\n\n' '- VS Code and Cursor extensions from `vscode/extensions.txt` and `cursor/extensions.txt`'
    printf '%s\n\n' "## Useful Commands"
    printf '```bash\n'
    printf './install.sh\n'
    printf 'DRY_RUN=true ./install.sh\n'
    printf 'dotfriend sync\n'
    printf './scripts/backup.sh --dry-run\n'
    printf './scripts/backup.sh --commit\n'
    printf './scripts/validate.sh --all\n'
    printf '```\n'
  } > "$out"

  log_ok "README.md generated"
}

# ─────────────────────────────────────────────────────────────
# Block builders (output bash code that gets appended to install.sh)
# ─────────────────────────────────────────────────────────────

_build_xcode_block() {
  local xcode; xcode="$(_jq_str "$SELECTIONS_FILE" '.xcode // false')"
  if [[ "$xcode" == "true" ]]; then
    printf "  if xcode-select -p >/dev/null 2>&1; then\n"
    printf "    log_ok \"Xcode CLI tools already installed\"\n"
    printf "  else\n"
    printf '    if [[ "$DRY_RUN" == "true" ]]; then\n'
    printf '      log_info "[dry-run] Would install Xcode CLI tools"\n'
    printf '    else\n'
    printf '      log_info "Installing Xcode Command Line Tools..."\n'
    printf '      xcode-select --install 2>/dev/null || true\n'
    printf '      until xcode-select -p >/dev/null 2>&1; do sleep 5; done\n'
    printf '      log_ok "Xcode CLI tools installed"\n'
    printf '    fi\n'
    printf '  fi\n'
  else
    printf "  # Xcode CLI tools skipped by user\n"
  fi
}

_build_symlinks_block() {
  local dotfiles; dotfiles="$(_jq_str "$SELECTIONS_FILE" '.dotfiles | if . then join("\n") else "" end')"
  printf "\n  # Dotfile symlinks\n"
  if [[ -n "$dotfiles" ]]; then
    while IFS= read -r df; do
      [[ -z "$df" ]] && continue
      local repo_path; repo_path="$(_repo_path_for_dotfile "$df")"
      printf '  _symlink "$DOTFILES_DIR/%s" "$HOME/%s"\n' "$repo_path" "$df"
    done <<< "$dotfiles"
  fi
}

_build_copies_block() {
  printf "\n  # App-managed files (copied, not symlinked)\n"
  local configs; configs="$(_jq_str "$SELECTIONS_FILE" '.config_dirs | if . then join("\n") else "" end')"
  if [[ -n "$configs" ]]; then
    while IFS= read -r cfg; do
      [[ -z "$cfg" ]] && continue
      printf '  _copy "$DOTFILES_DIR/config/%s" "$HOME/.config/%s"\n' "$cfg" "$cfg"
    done <<< "$configs"
  fi
  if [[ -d "${HOME}/Library/Preferences/com.choosyosx.Choosy.plist" ]]; then
    printf "  # Choosy preferences are plist-managed; skipping symlink\n"
  fi
}

_build_agent_rsync_block() {
  printf "\n  # Agent config restore\n"
  while IFS= read -r agent_id; do
    [[ -z "$agent_id" ]] && continue
    local canonical_dir
    canonical_dir="$(jq -r --arg id "$agent_id" '.agentic_tools[] | select(.id == $id) | .canonical_dir' "${SCRIPT_DIR}/agent-tools.json" 2>/dev/null || true)"
    if [[ -n "$canonical_dir" && "$canonical_dir" != "null" ]]; then
      local runtime_dir
      runtime_dir="${canonical_dir/#\~/\$HOME}"

      local important_files important_dirs
      important_files="$(jq -r --arg id "$agent_id" '.agentic_tools[] | select(.id == $id) | .important_files // [] | .[]' "${SCRIPT_DIR}/agent-tools.json" 2>/dev/null || true)"
      important_dirs="$(jq -r --arg id "$agent_id" '.agentic_tools[] | select(.id == $id) | .important_dirs // [] | .[]' "${SCRIPT_DIR}/agent-tools.json" 2>/dev/null || true)"

      while IFS= read -r file_path; do
        [[ -z "$file_path" ]] && continue
        printf '  if [[ -e "$DOTFILES_DIR/%s/%s" ]]; then\n' "$agent_id" "$file_path"
        printf '    _copy "$DOTFILES_DIR/%s/%s" "%s/%s"\n' "$agent_id" "$file_path" "$runtime_dir" "$file_path"
        printf "  fi\n"
      done <<< "$important_files"

      while IFS= read -r dir_path; do
        [[ -z "$dir_path" ]] && continue
        printf '  if [[ -d "$DOTFILES_DIR/%s/%s" ]]; then\n' "$agent_id" "$dir_path"
        printf '    _rsync_agent "$DOTFILES_DIR/%s/%s" "%s/%s"\n' "$agent_id" "$dir_path" "$runtime_dir" "$dir_path"
        printf "  fi\n"
      done <<< "$important_dirs"
    fi
  done < <(_selected_agent_ids)

  if [[ -d "${GEN_DIR}/agents/skills" ]]; then
    printf '  _rsync_agent "$DOTFILES_DIR/agents/skills" "$HOME/.agents/skills"\n'
  fi
  if [[ -d "${GEN_DIR}/agents/agent-docs" ]]; then
    printf '  _rsync_agent "$DOTFILES_DIR/agents/agent-docs" "$HOME/.agents/agent-docs"\n'
  fi
}

_build_npm_block() {
  local npm; npm="$(_jq_str "$SELECTIONS_FILE" '.npm_globals | if . then join("\n") else "" end')"
  printf "\n  # npm global packages\n"
  if [[ -n "$npm" ]]; then
    printf "  if command -v npm >/dev/null 2>&1; then\n"
    while IFS= read -r pkg; do
      [[ -z "$pkg" ]] && continue
      local pkg_name; pkg_name="${pkg%%@*}"
      printf "    soft_run npm install -g %s || true\n" "$pkg_name"
    done <<< "$npm"
    printf "  else\n"
    printf "    log_warn \"npm not found; skipping npm global installs\"\n"
    printf "  fi\n"
  fi
}

_build_vscode_block() {
  local editors; editors="$(_jq_str "$SELECTIONS_FILE" '.editors')"
  if [[ -n "$editors" ]] && command -v jq >/dev/null 2>&1; then
    local vscode; vscode="$(jq -r '.vscode // false' <<< "$editors" 2>/dev/null || true)"
    if [[ "$vscode" == "true" ]]; then
      printf "\n  # VS Code extensions\n"
      printf '  if command -v code >/dev/null 2>&1 && [[ -f "$DOTFILES_DIR/vscode/extensions.txt" ]]; then\n'
      printf "    while IFS= read -r ext; do\n"
      printf '      [[ -z "$ext" ]] && continue\n'
      printf '      soft_run code --install-extension "$ext" || true\n'
      printf '    done < "$DOTFILES_DIR/vscode/extensions.txt"\n'
      printf "  fi\n"
    fi
  fi
}

_build_cursor_block() {
  local editors; editors="$(_jq_str "$SELECTIONS_FILE" '.editors')"
  if [[ -n "$editors" ]] && command -v jq >/dev/null 2>&1; then
    local cursor; cursor="$(jq -r '.cursor // false' <<< "$editors" 2>/dev/null || true)"
    if [[ "$cursor" == "true" ]]; then
      printf "\n  # Cursor extensions\n"
      printf '  if command -v cursor >/dev/null 2>&1 && [[ -f "$DOTFILES_DIR/cursor/extensions.txt" ]]; then\n'
      printf "    while IFS= read -r ext; do\n"
      printf '      [[ -z "$ext" ]] && continue\n'
      printf '      soft_run cursor --install-extension "$ext" || true\n'
      printf '    done < "$DOTFILES_DIR/cursor/extensions.txt"\n'
      printf "  fi\n"
    fi
  fi
}

_build_dock_block() {
  local dock; dock="$(_jq_str "$SELECTIONS_FILE" '.dock')"
  printf "\n  # Dock restore\n"
  if [[ -n "$dock" ]] && command -v jq >/dev/null 2>&1; then
    local backup; backup="$(jq -r '.backup // false' <<< "$dock" 2>/dev/null || true)"
    if [[ "$backup" == "true" ]]; then
      printf '  if command -v dockutil >/dev/null 2>&1 && [[ -f "$DOTFILES_DIR/dock/dock-apps.txt" ]]; then\n'
      printf "    log_info \"Restoring Dock layout...\"\n"
      printf "    # Clear existing dock\n"
      printf "    dockutil --remove all --no-restart 2>/dev/null || true\n"
      printf "    while IFS= read -r app; do\n"
      printf '      [[ -z "$app" ]] && continue\n'
      printf '      soft_run dockutil --add "$app" --no-restart || true\n'
      printf '    done < "$DOTFILES_DIR/dock/dock-apps.txt"\n'
      printf "    killall Dock 2>/dev/null || true\n"
      printf "  else\n"
      printf "    log_warn \"dockutil not available; skipping dock restore\"\n"
      printf "  fi\n"
    fi
  fi
}

_build_duti_block() {
  local dock; dock="$(_jq_str "$SELECTIONS_FILE" '.dock')"
  printf "\n  # Default app associations\n"
  if [[ -n "$dock" ]] && command -v jq >/dev/null 2>&1; then
    local defaults; defaults="$(jq -r '.defaults // false' <<< "$dock" 2>/dev/null || true)"
    if [[ "$defaults" == "true" ]]; then
      printf "  if command -v duti >/dev/null 2>&1; then\n"
      printf "    log_info \"Setting default app associations...\"\n"
      printf "    # Add duti rules here as needed\n"
      printf "    # soft_run duti -s com.choosyosx.Choosy http all || true\n"
      printf "  else\n"
      printf "    log_warn \"duti not available; skipping default app associations\"\n"
      printf "  fi\n"
    fi
  fi
}

_build_telemetry_block() {
  local telemetry; telemetry="$(_jq_str "$SELECTIONS_FILE" '.telemetry // false')"
  printf "\n  # Telemetry disabling\n"
  if [[ "$telemetry" == "true" ]]; then
    printf '  if [[ "$DRY_RUN" == "true" ]]; then\n'
    printf '    log_info "[dry-run] Would disable telemetry"\n'
    printf '  else\n'
    printf '    log_info "Disabling telemetry..."\n'
    printf '    brew analytics off 2>/dev/null || true\n'
    printf '    go telemetry off 2>/dev/null || true\n'
    printf '    gh telemetry off 2>/dev/null || true\n'
    printf '    npm config set update-notifier false 2>/dev/null || true\n'
    printf '    # Bun telemetry\n'
    printf '    if [[ -f "%s/.bunfig.toml" ]]; then\n' "$HOME"
    printf '      grep -q telemetry "%s/.bunfig.toml" || printf "\\n[install]\\ntelemetry = false\\n" >> "%s/.bunfig.toml"\n' "$HOME" "$HOME"
    printf '    fi\n'
    printf '  fi\n'
  fi
}

# ─────────────────────────────────────────────────────────────
# Config copying
# ─────────────────────────────────────────────────────────────

_copy_configs() {
  local dotfiles; dotfiles="$(_jq_str "$SELECTIONS_FILE" '.dotfiles | if . then join("\n") else "" end')"
  if [[ -n "$dotfiles" ]]; then
    log_info "Copying dotfiles..."
    while IFS= read -r df; do
      [[ -z "$df" ]] && continue
      local src="${HOME}/${df}"
      local dest="${GEN_DIR}/$(_repo_path_for_dotfile "$df")"
      if [[ -f "$src" ]]; then
        ensure_dir "$(dirname "$dest")"
        cp "$src" "$dest"
        log_ok "Copied ~/${df}"
      fi
    done <<< "$dotfiles"
  fi

  # ~/.config directories
  local configs; configs="$(_jq_str "$SELECTIONS_FILE" '.config_dirs | if . then join("\n") else "" end')"
  if [[ -n "$configs" ]]; then
    log_info "Copying config directories..."
    while IFS= read -r cfg; do
      [[ -z "$cfg" ]] && continue
      local src="${HOME}/.config/${cfg}"
      local dest="${GEN_DIR}/config/${cfg}"
      if [[ -d "$src" ]]; then
        _copy_tree_filtered "$src" "$dest"
        log_ok "Copied ~/.config/${cfg}"
      fi
    done <<< "$configs"
  fi
}

_copy_editor_configs() {
  local editors; editors="$(_jq_str "$SELECTIONS_FILE" '.editors')"
  if [[ -z "$editors" ]]; then
    return 0
  fi

  if command -v jq >/dev/null 2>&1; then
    local vscode; vscode="$(jq -r '.vscode // false' <<< "$editors" 2>/dev/null || true)"
    if [[ "$vscode" == "true" ]]; then
      log_info "Copying VS Code settings..."
      local vscode_dir="${HOME}/Library/Application Support/Code/User"
      local dest="${GEN_DIR}/vscode"
      ensure_dir "$dest"
      if [[ -f "${vscode_dir}/settings.json" ]]; then
        cp "${vscode_dir}/settings.json" "${dest}/settings.json"
      fi
      if [[ -f "${vscode_dir}/keybindings.json" ]]; then
        cp "${vscode_dir}/keybindings.json" "${dest}/keybindings.json"
      fi
      if command -v code >/dev/null 2>&1; then
        code --list-extensions > "${dest}/extensions.txt" 2>/dev/null || true
      fi
      log_ok "VS Code settings backed up"
    fi

    local cursor; cursor="$(jq -r '.cursor // false' <<< "$editors" 2>/dev/null || true)"
    if [[ "$cursor" == "true" ]]; then
      log_info "Copying Cursor settings..."
      local cursor_dir="${HOME}/Library/Application Support/Cursor/User"
      local dest="${GEN_DIR}/cursor"
      ensure_dir "$dest"
      if [[ -f "${cursor_dir}/settings.json" ]]; then
        cp "${cursor_dir}/settings.json" "${dest}/settings.json"
      fi
      if [[ -f "${cursor_dir}/keybindings.json" ]]; then
        cp "${cursor_dir}/keybindings.json" "${dest}/keybindings.json"
      fi
      if command -v cursor >/dev/null 2>&1; then
        cursor --list-extensions > "${dest}/extensions.txt" 2>/dev/null || true
      fi
      log_ok "Cursor settings backed up"
    fi
  fi
}

_copy_agent_configs() {
  log_info "Copying agent tool configs..."
  while IFS= read -r agent_id; do
    [[ -z "$agent_id" ]] && continue

    # Look up canonical dir in agent-tools.json
    local canonical_dir
    canonical_dir="$(jq -r --arg id "$agent_id" '.agentic_tools[] | select(.id == $id) | .canonical_dir' "${SCRIPT_DIR}/agent-tools.json" 2>/dev/null || true)"
    if [[ -z "$canonical_dir" || "$canonical_dir" == "null" ]]; then
      log_warn "Unknown agent: $agent_id"
      continue
    fi

    canonical_dir="${canonical_dir/#\~/${HOME}}"
    if [[ ! -d "$canonical_dir" ]]; then
      log_warn "Agent dir not found: $canonical_dir"
      continue
    fi

    local dest="${GEN_DIR}/${agent_id}"
    ensure_dir "$dest"

    # Read important files and dirs
    local important_files important_dirs
    important_files="$(jq -r --arg id "$agent_id" '.agentic_tools[] | select(.id == $id) | .important_files // [] | .[]' "${SCRIPT_DIR}/agent-tools.json" 2>/dev/null || true)"
    important_dirs="$(jq -r --arg id "$agent_id" '.agentic_tools[] | select(.id == $id) | .important_dirs // [] | .[]' "${SCRIPT_DIR}/agent-tools.json" 2>/dev/null || true)"

    # Copy files
    while IFS= read -r f; do
      [[ -z "$f" ]] && continue
      local src="${canonical_dir}/${f}"
      if [[ -e "$src" && ! -L "$src" ]]; then
        cp -a "$src" "${dest}/"
        _sanitize_agent_file_copy "$agent_id" "${dest}/$(basename "$f")"
        log_ok "Copied ${f} for ${agent_id}"
      elif [[ -L "$src" ]]; then
        log_info "Skipping symlink: ${src}"
      fi
    done <<< "$important_files"

    # Copy dirs
    while IFS= read -r d; do
      [[ -z "$d" ]] && continue
      local src="${canonical_dir}/${d}"
      if [[ -d "$src" && ! -L "$src" ]]; then
        _copy_tree_filtered "$src" "${dest}/${d}"
        log_ok "Copied ${d}/ for ${agent_id}"
      elif [[ -L "$src" ]]; then
        log_info "Skipping symlinked dir: ${src}"
      fi
    done <<< "$important_dirs"
  done < <(_selected_agent_ids)

  if [[ -d "${HOME}/.agents/skills" ]]; then
    _copy_tree_filtered "${HOME}/.agents/skills" "${GEN_DIR}/agents/skills"
    log_ok "Copied ~/.agents/skills"
  fi
  if [[ -d "${HOME}/.agents/agent-docs" ]]; then
    _copy_tree_filtered "${HOME}/.agents/agent-docs" "${GEN_DIR}/agents/agent-docs"
    log_ok "Copied ~/.agents/agent-docs"
  fi
}

_copy_dock() {
  local dock; dock="$(_jq_str "$SELECTIONS_FILE" '.dock')"
  if [[ -z "$dock" ]]; then
    return 0
  fi

  if command -v jq >/dev/null 2>&1; then
    local backup; backup="$(jq -r '.backup // false' <<< "$dock" 2>/dev/null || true)"
    if [[ "$backup" == "true" ]]; then
      log_info "Backing up Dock layout..."
      local dest="${GEN_DIR}/dock"
      ensure_dir "$dest"
      if command -v dockutil >/dev/null 2>&1; then
        dockutil --list > "${dest}/dock-apps.txt" 2>/dev/null || true
        log_ok "Dock layout saved"
      else
        log_warn "dockutil not installed; skipping dock backup"
      fi
    fi
  fi
}

# ─────────────────────────────────────────────────────────────
# Scripts copying
# ─────────────────────────────────────────────────────────────

_copy_scripts() {
  log_info "Copying scripts..."
  local src_dir="${TEMPLATES_DIR}/scripts"
  local dest_dir="${GEN_DIR}/scripts"
  ensure_dir "$dest_dir"

  if [[ -d "$src_dir" ]]; then
    cp -a "${src_dir}/"* "$dest_dir/" 2>/dev/null || true
  fi

  # Also ensure lib dir exists
  ensure_dir "${dest_dir}/lib"

  chmod -R +x "${dest_dir}"/*.sh 2>/dev/null || true
  log_ok "Scripts copied"
}

# ─────────────────────────────────────────────────────────────
# Git operations
# ─────────────────────────────────────────────────────────────

_init_git() {
  log_info "Initializing git repository..."
  if [[ -d "${GEN_DIR}/.git" ]]; then
    log_warn "Local git repo already exists at ${GEN_DIR}"
    return 0
  fi

  local git_log
  git_log="$(mktemp)"

  if ! (
    cd "$GEN_DIR"
    git init
    git add .
    git commit -m "Initial dotfiles — generated by dotfriend"
  ) >"$git_log" 2>&1; then
    log_error "Could not initialize the local git repository"
    _print_command_failure_log "$git_log"
    rm -f "$git_log"
    return 1
  fi

  rm -f "$git_log"
  log_ok "Git repo initialized"
}

# ─────────────────────────────────────────────────────────────
# GitHub push
# ─────────────────────────────────────────────────────────────

_github_push() {
  local repo_name; repo_name="$(_selected_repo_name)"
  GEN_GITHUB_BACKED_UP="false"
  GEN_GITHUB_URL=""
  GEN_GITHUB_STATUS_MESSAGE=""
  if [[ -z "$repo_name" || "$repo_name" == "null" ]]; then
    GEN_GITHUB_STATUS_MESSAGE="GitHub backup was skipped because no repository name was configured."
    log_info "No GitHub repo configured; skipping push"
    return 0
  fi

  log_step "GitHub Backup"

  if ! command -v gh >/dev/null 2>&1; then
    GEN_GITHUB_STATUS_MESSAGE="GitHub backup was skipped because the gh CLI is not installed."
    log_warn "gh CLI not found; skipping GitHub push"
    return 0
  fi

  if ! gh auth status >/dev/null 2>&1; then
    GEN_GITHUB_STATUS_MESSAGE="GitHub backup was skipped because gh is not authenticated."
    log_warn "gh CLI not authenticated; run 'gh auth login' and try again"
    return 0
  fi

  local username
  username="$(gh api user -q '.login' 2>/dev/null || true)"
  if [[ -z "$username" || "$username" == "null" ]]; then
    GEN_GITHUB_STATUS_MESSAGE="GitHub backup was skipped because dotfriend could not determine your GitHub username."
    log_warn "Could not determine GitHub username"
    return 0
  fi

  if [[ "$GEN_DRY_RUN" == "true" ]]; then
    GEN_GITHUB_STATUS_MESSAGE="[dry-run] Would create GitHub repo ${username}/${repo_name}"
    log_info "[dry-run] Would create GitHub repo ${username}/${repo_name}"
    return 0
  fi

  GEN_GITHUB_URL="https://github.com/${username}/${repo_name}"

  if gh repo view "${username}/${repo_name}" >/dev/null 2>&1; then
    local push_log
    push_log="$(mktemp)"

    log_warn "GitHub repo already exists: ${username}/${repo_name}"
    if ! (
      cd "$GEN_DIR"
      git remote add origin "https://github.com/${username}/${repo_name}.git" 2>/dev/null || true
      git branch -M main 2>/dev/null || true
      git push -u origin main || git push -u origin master
    ) >"$push_log" 2>&1; then
      GEN_GITHUB_STATUS_MESSAGE="The local repo was generated, but dotfriend could not push it to ${GEN_GITHUB_URL}."
      log_warn "Could not push to ${GEN_GITHUB_URL}"
      _print_command_failure_log "$push_log"
      rm -f "$push_log"
      return 0
    fi

    rm -f "$push_log"
    GEN_GITHUB_BACKED_UP="true"
    GEN_GITHUB_STATUS_MESSAGE="Backed up to ${GEN_GITHUB_URL}"
    log_ok "Pushed to ${GEN_GITHUB_URL}"
    return 0
  fi

  local create_title="Creating private GitHub repo: ${username}/${repo_name}"
  local gh_create_log
  gh_create_log="$(mktemp)"
  if [[ "$GUM_AVAILABLE" == true ]]; then
    if ! (
      cd "$GEN_DIR"
      gum_spin --title "$create_title" --show-error -- \
        gh repo create "$repo_name" --private --source=. --push
    ); then
      GEN_GITHUB_STATUS_MESSAGE="The local repo was generated, but dotfriend could not create ${GEN_GITHUB_URL}."
      log_warn "GitHub repo creation failed for ${username}/${repo_name}"
      rm -f "$gh_create_log"
      return 1
    fi
  else
    log_info "$create_title"
    if ! (
      cd "$GEN_DIR"
      gh repo create "$repo_name" --private --source=. --push
    ) >"$gh_create_log" 2>&1; then
      GEN_GITHUB_STATUS_MESSAGE="The local repo was generated, but dotfriend could not create ${GEN_GITHUB_URL}."
      log_warn "GitHub repo creation failed for ${username}/${repo_name}"
      _print_command_failure_log "$gh_create_log"
      rm -f "$gh_create_log"
      return 1
    fi
  fi

  rm -f "$gh_create_log"
  GEN_GITHUB_BACKED_UP="true"
  GEN_GITHUB_STATUS_MESSAGE="Backed up to ${GEN_GITHUB_URL}"
  log_ok "Pushed to ${GEN_GITHUB_URL}"
}

# ─────────────────────────────────────────────────────────────
# Main generator entry point
# ─────────────────────────────────────────────────────────────

generate_repo() {
  local target_dir="${1-}"
  local dry_run="${2:-false}"
  local repo_name; repo_name="$(_selected_repo_name)"

  # Ensure we always use an absolute path
  if [[ -z "$target_dir" ]]; then
    target_dir="${HOME}/${repo_name}"
  fi

  GEN_DIR="$target_dir"
  GEN_BACKUP_ROOT="${HOME}/.dotfiles-backup"
  GEN_DRY_RUN="$dry_run"
  GEN_GITHUB_BACKED_UP="false"
  GEN_GITHUB_URL=""
  GEN_GITHUB_STATUS_MESSAGE=""

  if [[ "$dry_run" == "true" ]]; then
    log_info "[dry-run] Would generate repo at ${GEN_DIR}"
    return 0
  fi

  if [[ -d "$GEN_DIR" && -n "$(ls -A "$GEN_DIR" 2>/dev/null)" ]]; then
    if ! gum_confirm "${GEN_DIR} already exists and is not empty. Overwrite?"; then
      log_error "Aborting"
      return 1
    fi
  fi

  ensure_dir "$GEN_DIR"
  ensure_dir "${GEN_DIR}/scripts/lib"
  ensure_dir "${GEN_DIR}/config"
  ensure_dir "${GEN_DIR}/config/git"
  ensure_dir "${GEN_DIR}/zsh"
  ensure_dir "${GEN_DIR}/vscode"
  ensure_dir "${GEN_DIR}/cursor"
  ensure_dir "${GEN_DIR}/claude"
  ensure_dir "${GEN_DIR}/codex"
  ensure_dir "${GEN_DIR}/agents/skills"
  ensure_dir "${GEN_DIR}/agents/agent-docs"
  ensure_dir "${GEN_DIR}/dock"

  log_step "Generating dotfiles repository"
  log_info "Target directory: ${GEN_DIR}"

  _generate_brewfile
  _generate_install_sh
  _generate_bootstrap_sh
  _generate_gitignore
  _generate_locations_md
  _generate_repo_metadata
  _generate_readme_md

  _copy_configs
  _copy_editor_configs
  _copy_agent_configs
  _copy_dock
  _copy_scripts
  _generate_restore_manifest

  _init_git
  _github_push

  log_step "All set"
  if [[ "$GEN_GITHUB_BACKED_UP" == "true" ]]; then
    log_ok "Your dotfiles repo has been generated and backed up to GitHub."
  else
    log_ok "Your dotfiles repo has been generated."
    if [[ -n "$GEN_GITHUB_STATUS_MESSAGE" ]]; then
      log_info "$GEN_GITHUB_STATUS_MESSAGE"
    fi
  fi
  log_info "Local repo: ${GEN_DIR}"
  if [[ -n "$GEN_GITHUB_URL" ]]; then
    log_info "GitHub: ${GEN_GITHUB_URL}"
  fi
  log_info "To sync future changes from this Mac, run: dotfriend sync"
}
