#!/usr/bin/env bash
# dotfiles bootstrap.sh — First-run setup for brand-new Macs
# Generated by dotfriend. Edit with care.
# shellcheck shell=bash

set -euo pipefail

# ─────────────────────────────────────────────────────────────
# Environment toggles
# ─────────────────────────────────────────────────────────────

REPO_URL="{{REPO_URL}}"
DOTFILES_DIR="{{DOTFILES_DIR}}"
RUN_DOTFILES_INSTALL="{{RUN_DOTFILES_INSTALL:-true}}"

# ─────────────────────────────────────────────────────────────
# Helpers
# ─────────────────────────────────────────────────────────────

log_info()  { printf "\\033[34mℹ\\033[0m  %s\\n" "$*"; }
log_ok()    { printf "\\033[32m✔\\033[0m  %s\\n" "$*"; }
log_warn()  { printf "\\033[33m⚠\\033[0m  %s\\n" "$*" >&2; }
log_error() { printf "\\033[31m✖\\033[0m  %s\\n" "$*" >&2; }
log_step()  { printf "\\n\\033[1;36m→ %s\\033[0m\\n" "$*"; }

ensure_dir() { [[ -d "$1" ]] || mkdir -p "$1"; }

brew_prefix() {
  if [[ -d /opt/homebrew/bin ]]; then
    printf '%s' '/opt/homebrew'
  elif [[ -d /usr/local/bin ]]; then
    printf '%s' '/usr/local'
  else
    printf '%s' "$HOME/homebrew"
  fi
}

# ─────────────────────────────────────────────────────────────
# Xcode Command Line Tools
# ─────────────────────────────────────────────────────────────

install_xcode_cli() {
  if xcode-select -p >/dev/null 2>&1; then
    log_ok "Xcode Command Line Tools already installed"
    return 0
  fi
  log_info "Installing Xcode Command Line Tools..."
  xcode-select --install 2>/dev/null || true
  log_warn "Please complete the Xcode CLI tools installation dialog, then re-run this script."
  log_warn "Alternatively, wait and the script will continue once tools are available."
  # Wait for installation
  until xcode-select -p >/dev/null 2>&1; do
    sleep 5
  done
  log_ok "Xcode Command Line Tools installed"
}

# ─────────────────────────────────────────────────────────────
# Homebrew
# ─────────────────────────────────────────────────────────────

install_homebrew() {
  if command -v brew >/dev/null 2>&1; then
    log_ok "Homebrew already installed"
    return 0
  fi
  log_info "Installing Homebrew..."
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
}

persist_homebrew_shellenv() {
  local prefix; prefix="$(brew_prefix)"
  local shellenv; shellenv="eval \"$(${prefix}/bin/brew shellenv)\""
  local zprofile="${HOME}/.zprofile"

  if [[ -f "$zprofile" ]] && grep -q "brew shellenv" "$zprofile" 2>/dev/null; then
    log_ok "Homebrew shellenv already in ~/.zprofile"
    return 0
  fi

  log_info "Persisting Homebrew shellenv to ~/.zprofile..."
  printf "\n# Homebrew\n%s\n" "$shellenv" >> "$zprofile" || log_warn "Failed to append to $zprofile"
  log_ok "Done"
}

# ─────────────────────────────────────────────────────────────
# Base packages
# ─────────────────────────────────────────────────────────────

install_base_packages() {
  log_step "Installing base packages"
  local prefix; prefix="$(brew_prefix)"

  # Ensure brew is in PATH for this session
  if [[ -x "${prefix}/bin/brew" ]]; then
    eval "$(${prefix}/bin/brew shellenv)"
  fi

  # git
  if ! command -v git >/dev/null 2>&1; then
    log_info "Installing git..."
    brew install git || { log_error "Failed to install git"; }
  fi

  # gh
  if ! command -v gh >/dev/null 2>&1; then
    log_info "Installing gh..."
    brew install gh || { log_error "Failed to install gh"; }
  fi

  # gum
  if ! command -v gum >/dev/null 2>&1; then
    log_info "Installing gum..."
    brew install gum || { log_error "Failed to install gum"; }
  fi

  # No base casks are required during bootstrap.
}

# ─────────────────────────────────────────────────────────────
# Clone dotfiles repo
# ─────────────────────────────────────────────────────────────

clone_dotfiles() {
  log_step "Cloning dotfiles repository"
  if [[ -d "$DOTFILES_DIR" ]]; then
    log_warn "Directory ${DOTFILES_DIR} already exists."
    log_warn "If you want to re-run, please remove it first or run install.sh directly."
    return 0
  fi
  ensure_dir "$(dirname "$DOTFILES_DIR")"
  git clone "$REPO_URL" "$DOTFILES_DIR" || {
    log_error "Failed to clone $REPO_URL"
    return 1
  }
  log_ok "Cloned to ${DOTFILES_DIR}"
}

# ─────────────────────────────────────────────────────────────
# Hand off to install.sh
# ─────────────────────────────────────────────────────────────

run_install() {
  if [[ "$RUN_DOTFILES_INSTALL" != "true" ]]; then
    log_info "Skipping install.sh (set RUN_DOTFILES_INSTALL=true to auto-run)"
    log_info "You can run it manually later:"
    log_info "  ${DOTFILES_DIR}/install.sh"
    return 0
  fi
  local install_script="${DOTFILES_DIR}/install.sh"
  if [[ -x "$install_script" ]]; then
    log_step "Running install.sh..."
    "$install_script"
  else
    log_warn "install.sh not found at ${install_script}"
  fi
}

# ─────────────────────────────────────────────────────────────
# Main
# ─────────────────────────────────────────────────────────────

main() {
  log_step "dotfriend bootstrap"
  log_info "Setting up your new Mac..."

  install_xcode_cli
  install_homebrew
  persist_homebrew_shellenv
  install_base_packages
  clone_dotfiles
  run_install

  log_step "Bootstrap complete!"
  log_info "Your dotfiles are at: ${DOTFILES_DIR}"
}

main "$@"
