#!/usr/bin/env bash
# dotfiles install.sh — Full restore script
# Generated by dotfriend. Edit with care.
# shellcheck shell=bash

set -euo pipefail

# ─────────────────────────────────────────────────────────────
# Environment toggles
# ─────────────────────────────────────────────────────────────

INSTALL_MAS="{{INSTALL_MAS:-true}}"
BREW_UPGRADE="{{BREW_UPGRADE:-true}}"
INSTALL_DOTFRIEND="{{INSTALL_DOTFRIEND:-true}}"
INSTALL_VALIDATE="{{INSTALL_VALIDATE:-false}}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DOTFILES_DIR="${DOTFILES_DIR:-${SCRIPT_DIR}}"
BACKUP_ROOT="{{BACKUP_ROOT:-${HOME}/.dotfiles-backup}}"
DRY_RUN="{{DRY_RUN:-false}}"

# ─────────────────────────────────────────────────────────────
# State
# ─────────────────────────────────────────────────────────────

ERRORS=()
WARNINGS=()

# ─────────────────────────────────────────────────────────────
# Helpers
# ─────────────────────────────────────────────────────────────

log_info()  { printf "\\033[34mℹ\\033[0m  %s\\n" "$*"; }
log_ok()    { printf "\\033[32m✔\\033[0m  %s\\n" "$*"; }
log_warn()  { printf "\\033[33m⚠\\033[0m  %s\\n" "$*" >&2; WARNINGS+=("$*"); }
log_error() { printf "\\033[31m✖\\033[0m  %s\\n" "$*" >&2; ERRORS+=("$*"); }
log_step()  { printf "\\n\\033[1;36m→ %s\\033[0m\\n" "$*"; }

ensure_dir() { [[ -d "$1" ]] || mkdir -p "$1"; }

# Run a command, but on failure log the error and continue
soft_run() {
  if [[ "$DRY_RUN" == "true" ]]; then
    printf "  [dry-run] would run: %s\\n" "$*"
    return 0
  fi
  if "$@"; then
    return 0
  else
    log_error "Command failed: $*"
    return 1
  fi
}

backup_file() {
  local src="$1"
  if [[ ! -e "$src" ]]; then
    return 0
  fi
  ensure_dir "$BACKUP_ROOT"
  local dest="${BACKUP_ROOT}/$(basename "$src")-$(date +%Y%m%d-%H%M%S)"
  cp -a "$src" "$dest"
  log_info "Backed up $(basename "$src") → ${dest}"
}

brew_prefix() {
  if [[ -d /opt/homebrew/bin ]]; then
    printf '%s' '/opt/homebrew'
  elif [[ -d /usr/local/bin ]]; then
    printf '%s' '/usr/local'
  else
    printf '%s' "$HOME/homebrew"
  fi
}

json_escape() {
  local value="$1"
  value="${value//\\/\\\\}"
  value="${value//\"/\\\"}"
  value="${value//$'\n'/\\n}"
  printf '%s' "$value"
}

# ─────────────────────────────────────────────────────────────
# Phase 0: Sudo keepalive
# ─────────────────────────────────────────────────────────────

start_sudo_keepalive() {
  if [[ "$DRY_RUN" == "true" ]]; then
    log_info "[dry-run] Would start sudo keepalive"
    return 0
  fi
  sudo -v
  while true; do
    sudo -n true
    sleep 60
    kill -0 "$$" || exit
  done 2>/dev/null &
}

# ─────────────────────────────────────────────────────────────
# Phase 1: Prerequisites
# ─────────────────────────────────────────────────────────────

phase_prerequisites() {
  log_step "Phase 1: Prerequisites"

  # Homebrew
  if ! command -v brew >/dev/null 2>&1; then
    if [[ "$DRY_RUN" == "true" ]]; then
      log_info "[dry-run] Would install Homebrew"
    else
      log_info "Installing Homebrew..."
      /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)" || {
        log_error "Homebrew installation failed"
        return 1
      }
    fi
  fi

  # Homebrew shellenv
  local prefix; prefix="$(brew_prefix)"
  if [[ -x "${prefix}/bin/brew" ]]; then
    eval "$(${prefix}/bin/brew shellenv)" || log_warn "Failed to eval brew shellenv"
  fi

  # Xcode CLI tools
  {{XCODE_BLOCK}}

  # Upgrade if requested
  if [[ "$BREW_UPGRADE" == "true" ]]; then
    soft_run brew update
    soft_run brew upgrade
  fi
}

# ─────────────────────────────────────────────────────────────
# Phase 1.5: dotfriend CLI
# ─────────────────────────────────────────────────────────────

phase_dotfriend() {
  log_step "Phase 1.5: dotfriend CLI"

  if [[ "$INSTALL_DOTFRIEND" != "true" ]]; then
    log_info "Skipping dotfriend install (INSTALL_DOTFRIEND=false)"
    record_dotfriend_repo
    return 0
  fi

  if command -v dotfriend >/dev/null 2>&1; then
    log_ok "dotfriend already installed"
    record_dotfriend_repo
    return 0
  fi

  if ! command -v npm >/dev/null 2>&1; then
    log_info "npm not found; installing Node.js so dotfriend can be installed"
    soft_run brew install node || true
  fi

  if command -v npm >/dev/null 2>&1; then
    soft_run npm install -g dotfriend || true
  else
    log_warn "npm still not found; dotfriend CLI was not installed"
  fi

  record_dotfriend_repo
}

record_dotfriend_repo() {
  local cache_dir="${HOME}/.cache/dotfriend"
  local cache_file="${cache_dir}/last-sync.json"
  local remote_url=""
  local branch=""
  local installed_at
  installed_at="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

  if [[ -d "${DOTFILES_DIR}/.git" ]] && command -v git >/dev/null 2>&1; then
    remote_url="$(git -C "$DOTFILES_DIR" config --get remote.origin.url 2>/dev/null || true)"
    branch="$(git -C "$DOTFILES_DIR" branch --show-current 2>/dev/null || true)"
  fi

  if [[ "$DRY_RUN" == "true" ]]; then
    log_info "[dry-run] Would record ${DOTFILES_DIR} as the dotfriend sync repo"
    return 0
  fi

  ensure_dir "$cache_dir"
  printf '{"repo_dir":"%s","remote_url":"%s","branch":"%s","installed_at":"%s"}\n' \
    "$(json_escape "$DOTFILES_DIR")" \
    "$(json_escape "$remote_url")" \
    "$(json_escape "$branch")" \
    "$(json_escape "$installed_at")" > "$cache_file" || {
      log_warn "Could not write dotfriend sync cache at ${cache_file}"
      return 0
    }
  log_ok "Registered ${DOTFILES_DIR} for dotfriend sync"
}

# ─────────────────────────────────────────────────────────────
# Phase 2: Configuration (symlinks, copies, rsyncs)
# ─────────────────────────────────────────────────────────────

phase_configuration() {
  log_step "Phase 2: Configuration"

  ensure_dir "$BACKUP_ROOT"

  # Symlinks
  {{SYMLINKS_BLOCK}}

  # Copies (app-managed files)
  {{COPIES_BLOCK}}

  # Agent configs (rsync --delete)
  {{AGENT_RSYNC_BLOCK}}
}

_symlink() {
  local src="$1" dest="$2"
  if [[ "$DRY_RUN" == "true" ]]; then
    printf "  [dry-run] would symlink %s → %s\\n" "$dest" "$src"
    return 0
  fi
  if [[ -L "$dest" && "$(readlink "$dest")" == "$src" ]]; then
    log_ok "Already linked: $dest"
    return 0
  fi
  if [[ -e "$dest" || -L "$dest" ]]; then
    backup_file "$dest" || true
    rm -rf "$dest" || { log_error "Failed to remove $dest"; return 1; }
  fi
  ln -s "$src" "$dest" || { log_error "Failed to symlink $dest"; return 1; }
  log_ok "Linked $dest → $src"
}

_copy() {
  local src="$1" dest="$2"
  if [[ "$DRY_RUN" == "true" ]]; then
    printf "  [dry-run] would copy %s → %s\\n" "$src" "$dest"
    return 0
  fi
  if [[ -e "$dest" ]]; then
    backup_file "$dest"
  fi
  cp -a "$src" "$dest" || { log_error "Failed to copy $src to $dest"; return 1; }
  log_ok "Copied $src → $dest"
}

_rsync_agent() {
  local src="$1" dest="$2"
  if [[ "$DRY_RUN" == "true" ]]; then
    printf "  [dry-run] would rsync --delete %s/ → %s/\\n" "$src" "$dest"
    return 0
  fi
  ensure_dir "$dest"
  rsync -a --delete "${src}/" "${dest}/" || { log_error "Failed to rsync $src to $dest"; return 1; }
  log_ok "Rsynced $src → $dest"
}

# ─────────────────────────────────────────────────────────────
# Phase 3: App Setup (Brewfile, npm, extensions)
# ─────────────────────────────────────────────────────────────

phase_apps() {
  log_step "Phase 3: App Setup"

  # Brewfile
  local brewfile="${DOTFILES_DIR}/Brewfile"
  if [[ -f "$brewfile" ]]; then
    if [[ "$DRY_RUN" == "true" ]]; then
      log_info "[dry-run] Would brew bundle from ${brewfile}"
    else
      log_info "Installing from Brewfile..."
      # Install line-by-line for soft-fail
      while IFS= read -r line || [[ -n "$line" ]]; do
        line="$(printf '%s' "$line" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')"
        [[ -z "$line" || "$line" == \#* ]] && continue
        local item; item="$(printf '%s' "$line" | sed 's/^[^"]*"\([^"]*\)".*/\1/')"
        if [[ "$line" == tap* ]]; then
          printf "  Installing tap: %s\\n" "$item"
          soft_run brew tap "$item" || true
        elif [[ "$line" == brew* ]]; then
          printf "  Installing formula: %s\\n" "$item"
          soft_run brew install "$item" || true
        elif [[ "$line" == cask* ]]; then
          printf "  Installing cask: %s\\n" "$item"
          soft_run brew install --cask "$item" || true
        elif [[ "$line" == mas* ]]; then
          if [[ "$INSTALL_MAS" == "true" ]]; then
            local app_id; app_id="$(printf '%s' "$line" | grep -oE '[0-9]+' | head -n1)"
            printf "  Installing MAS app: %s\\n" "$app_id"
            soft_run mas install "$app_id" || true
          else
            log_warn "Skipping MAS app: $item (INSTALL_MAS=false)"
          fi
        fi
      done < "$brewfile"
    fi
  fi

  # npm globals
  {{NPM_BLOCK}}

  # VS Code extensions
  {{VSCODE_BLOCK}}

  # Cursor extensions
  {{CURSOR_BLOCK}}
}

# ─────────────────────────────────────────────────────────────
# Phase 4: Final Setup (dock, defaults, telemetry)
# ─────────────────────────────────────────────────────────────

phase_final() {
  log_step "Phase 4: Final Setup"

  # Dock restore
  {{DOCK_BLOCK}}

  # Default app associations
  {{DUTI_BLOCK}}

  # Telemetry
  {{TELEMETRY_BLOCK}}

  # coreutils sha256sum symlink
  if command -v gsha256sum >/dev/null 2>&1 && ! command -v sha256sum >/dev/null 2>&1; then
    local bp; bp="$(brew_prefix)"
    if [[ "$DRY_RUN" == "true" ]]; then
      log_info "[dry-run] Would symlink sha256sum → gsha256sum"
    else
      ln -sf "${bp}/opt/coreutils/libexec/gnubin/gsha256sum" "${bp}/bin/sha256sum" 2>/dev/null || true
    fi
  fi
}

# ─────────────────────────────────────────────────────────────
# Phase 5: Validation
# ─────────────────────────────────────────────────────────────

phase_validation() {
  if [[ "$INSTALL_VALIDATE" != "true" ]]; then
    log_info "Skipping validation (set INSTALL_VALIDATE=true to enable)"
    return 0
  fi
  log_step "Phase 5: Validation"
  local validate_script="${DOTFILES_DIR}/scripts/validate.sh"
  if [[ -x "$validate_script" ]]; then
    soft_run "$validate_script" || true
  else
    log_warn "validate.sh not found or not executable"
  fi
}

# ─────────────────────────────────────────────────────────────
# Error summary
# ─────────────────────────────────────────────────────────────

print_summary() {
  printf "\\n"
  if [[ ${#ERRORS[@]} -gt 0 ]]; then
    printf "\\033[1;31m%d error(s) occurred:\\033[0m\\n" "${#ERRORS[@]}"
    for e in "${ERRORS[@]}"; do
      printf "  ✖ %s\\n" "$e"
    done
  fi
  if [[ ${#WARNINGS[@]} -gt 0 ]]; then
    printf "\\033[1;33m%d warning(s):\\033[0m\\n" "${#WARNINGS[@]}"
    for w in "${WARNINGS[@]}"; do
      printf "  ⚠ %s\\n" "$w"
    done
  fi
  if [[ ${#ERRORS[@]} -eq 0 && ${#WARNINGS[@]} -eq 0 ]]; then
    printf "\\033[1;32m✔ All done!\\033[0m\\n"
  fi
}

# ─────────────────────────────────────────────────────────────
# Main
# ─────────────────────────────────────────────────────────────

main() {
  # Parse args
  for arg in "$@"; do
    case "$arg" in
      --dry-run) DRY_RUN=true ;;
    esac
  done

  start_sudo_keepalive
  phase_prerequisites
  phase_dotfriend
  phase_configuration
  phase_apps
  phase_final
  phase_validation
  print_summary
}

main "$@"
